name: GitHub Actions Demo Java CI

on: [push]

jobs:
    Explore-GitHub-Action-Java-CI:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '8'
            distribution: 'adopt'
        - name: Build with Maven
          run: mvn verify -fae -DskipITs
        - name: Report Status
          run: echo "This job's status is ${{ job.status }}."
