name: GitHub Actions Demo Java CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Dependencies
        run: mvn install

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Building Project
        run: mvn clean compile
        
      - name: Run Unit Tests
        run: mvn verify -fae -DskipITs
        
      - name: Report Status
        run: echo "This job's status is ${{ job.status }}."

  release:
    runs-on: ubuntu-latest
    needs: [verify, test]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Setup Extensions
        uses: actions/checkout@v3
        
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          
      - name: Release Using Semantic Release
        run:
          sudo apt-get update
          sudo apt-get install python
          pip install --user bumpversion
          npm install @semantic-release/changelog
          npm install @semantic-release/exec
          npm install @semantic-release/git
          npm install @semantic-release/github
          npx semantic-release
