name: GitHub Actions Demo Java CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Install Dependencies
        run: mvn install

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Building Project
        run: mvn clean compile
        
      - name: Run Unit Tests
        run: mvn verify -fae -DskipITs
        
      - name: Report Status
        run: echo "This job's status is ${{ job.status }}."
        
      - name: Echo GitHub Ref
        run: echo "The GitHub Ref is ${{ github.ref }}."
      - name: Echo Commit Message
        run: echo "The Commit Message is ${{ github.event.head_commit.message }}."
      - name: Echo GitHub Event Name
        run: echo "The GitHub Event name is ${{ github.event_name }}."

  release:
    runs-on: ubuntu-latest
    needs: [verify, test]
    if: "github.event_name == 'push' && github.ref == 'refs/heads/master' && !startsWith(github.event.head_commit.message, 'chore')"
    permissions: write-all
    steps:
      - name: Setup Extensions
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Install Semantic Release dependencies
        run: |
          pip3 install --user bump2version
          npm install -g semantic-release
          npm install -g @semantic-release/changelog
          npm install -g @semantic-release/exec
          npm install -g @semantic-release/git
          npm install -g @semantic-release/github
          
      - name: Publish to Git Releases and Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run:
          npx semantic-release

  publish:
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && contains(github.ref, 'refs/tags')"
    steps:
      - name: Set Up Extensions
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
